/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yarin_android_HelloNDK_Jni */


#ifdef __cplusplus
extern "C" {
#endif

jint android_text_StaticLayout_getcurrentsplitnum
  (JNIEnv *, jobject, jstring);


jint android_text_StaticLayout_getnextsplitnum
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif

