/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oppo_kinectlib_ActionRemind */

#ifndef _Included_com_oppo_kinectlib_ActionRemind
#define _Included_com_oppo_kinectlib_ActionRemind
#ifdef __cplusplus
extern "C" {
#endif
#undef com_oppo_kinectlib_ActionRemind_GSENSOR_INTERRUPT_ENABLE
#define com_oppo_kinectlib_ActionRemind_GSENSOR_INTERRUPT_ENABLE 1L
#undef com_oppo_kinectlib_ActionRemind_GSENSOR_INTERRUPT_DISABLE
#define com_oppo_kinectlib_ActionRemind_GSENSOR_INTERRUPT_DISABLE 0L
/*
 * Class:     com_oppo_kinectlib_ActionRemind
 * Method:    nativeSetGsensorInterruptEn
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionRemind_nativeSetGsensorInterruptEn
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_oppo_kinectlib_ActionRemind
 * Method:    nativeGetGsensorInterruptTrue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_oppo_kinectlib_ActionRemind_nativeGetGsensorInterruptTrue
  (JNIEnv *, jobject);

/*
 * Class:     com_oppo_kinectlib_ActionRemind
 * Method:    nativeSetGsensorInterruptTrue
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionRemind_nativeSetGsensorInterruptTrue
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
