/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oppo_kinectlib_ActionPickUp */

#ifndef _Included_com_oppo_kinectlib_ActionPickUp
#define _Included_com_oppo_kinectlib_ActionPickUp
#ifdef __cplusplus
extern "C" {
#endif
#undef com_oppo_kinectlib_ActionPickUp_DBG
#define com_oppo_kinectlib_ActionPickUp_DBG 1L
#if 0 //canjie.zheng modify for distinguishing ActionPickUp by gyroscope 2013-03-18
/*
 * Class:     com_oppo_kinectlib_ActionPickUp
 * Method:    nativeReceiveAccData
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionPickUp_nativeReceiveAccData
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_oppo_kinectlib_ActionPickUp
 * Method:    nativeReceiveDisData
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionPickUp_nativeReceiveDisData
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);
#else
//canjie.zheng add
/*
 * Class:     com_oppo_kinectlib_ActionPickUp
 * Method:    nativeReceiveDisData
 * Signature: (FFF)V
 */

JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionPickUp_nativeReceiveGyrData
	(JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);
//add end
#endif
/*
 * Class:     com_oppo_kinectlib_ActionPickUp
 * Method:    nativeInit
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionPickUp_nativeInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
