/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oppo_kinectlib_ActionBringToEar */

#ifndef _Included_com_oppo_kinectlib_ActionBringToEar
#define _Included_com_oppo_kinectlib_ActionBringToEar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oppo_kinectlib_ActionBringToEar
 * Method:    nativeReceiveAccData
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionBringToEar_nativeReceiveAccData
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);
  
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionBringToEar_nativeReceiveDisData
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

#if 1//canjie.zheng add for gyroscope 
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionBringToEar_nativeReceiveGyrData
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

#endif //end
#ifdef __cplusplus
}
#endif
#endif
