/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oppo_kinectlib_ActionTurn */

#ifndef _Included_com_oppo_kinectlib_ActionTurn
#define _Included_com_oppo_kinectlib_ActionTurn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oppo_kinectlib_ActionTurn
 * Method:    nativeReceiveAccData
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionTurn_nativeReceiveAccData
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_oppo_kinectlib_ActionTurn
 * Method:    nativeInit
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionTurn_nativeInit
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
