/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oppo_kinectlib_ActionSwing */

#ifndef _Included_com_oppo_kinectlib_ActionSwing
#define _Included_com_oppo_kinectlib_ActionSwing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oppo_kinectlib_ActionSwing
 * Method:    nativeReceiveGyrData
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionSwing_nativeReceiveGyrData
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_oppo_kinectlib_ActionSwing
 * Method:    nativeInit
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionSwing_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_oppo_kinectlib_ActionSwing
 * Method:    nativeSetparameter
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_oppo_kinectlib_ActionSwing_nativeSetparameter
  (JNIEnv *, jobject, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
