/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oppo_kinectlib_ActionLean */

#ifndef _Included_com_oppo_kinectlib_ActionLean
#define _Included_com_oppo_kinectlib_ActionLean
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oppo_kinectlib_ActionLean
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionLean_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_oppo_kinectlib_ActionLean
 * Method:    nativeSetparameter
 * Signature: ([FI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_oppo_kinectlib_ActionLean_nativeSetparameter
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_oppo_kinectlib_ActionLean
 * Method:    nativeReceiveAccData
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionLean_nativeReceiveAccData
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
