/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oppo_kinectlib_ActionRemind_MyBroadcastReceiver */

#ifndef _Included_com_oppo_kinectlib_ActionRemind_MyBroadcastReceiver
#define _Included_com_oppo_kinectlib_ActionRemind_MyBroadcastReceiver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
