/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oppo_kinectlib_ActionStatic */

#ifndef _Included_com_oppo_kinectlib_ActionStatic
#define _Included_com_oppo_kinectlib_ActionStatic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oppo_kinectlib_ActionStatic
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionStatic_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_oppo_kinectlib_ActionStatic
 * Method:    nativeReceiveAccData
 * Signature: (FFF)V
 */
#if 0 //canjie.zheng modified for distinguishing ActionStatic by gyroscope 2013-03-18
JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionStatic_nativeReceiveAccData
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);
#else
 JNIEXPORT void JNICALL Java_com_oppo_kinectlib_ActionStatic_nativeReceiveGyrData
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);
#endif //canjie.zheng end

#ifdef __cplusplus
}
#endif
#endif
