/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oppo_book_BookPageTurnEffect */

#ifndef _Included_com_oppo_book_BookPageTurnEffect
#define _Included_com_oppo_book_BookPageTurnEffect
#ifdef __cplusplus
extern "C" {
#endif
//return mMiddleX	mMiddleY mFolderY2	mFolderX2	mFolderY22	mFolderX22 mFolderX1
//mFolderY1 mFolderY11 mFolderX11 mTouchToCornerDis mShadowX1 mShadowY1 mShadowY2 mShadowX2
/*
 * Class:     com_oppo_book_BookPageTurnEffect
 * Method:    getCalcPoints
 * Signature: (FFFFIIII)[F
 */
JNIEXPORT jfloatArray getCalcPoints
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint);

//return mFolderX33 mFolderY33 mFolderX44 mFolderY44
/*
 * Class:     com_oppo_book_BookPageTurnEffect12
 * Method:    getCalcInsectionPoint
 * Signature: (FFFFFFFFFF)[F
 */
JNIEXPORT jfloatArray JNICALL getCalcInsectionPoint
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);
#ifdef __cplusplus
}
#endif
#endif