include $(CLEAR_VARS)
LOCAL_MODULE       := $(SINGLE_TARGET)
LOCAL_MODULE_TAGS  := $(SINGLE_MODULE_TAGS)
LOCAL_MODULE_CLASS := APPS
#system/app
LOCAL_MODULE_PATH  :=$(TARGET_OUT)/app
LOCAL_CERTIFICATE  := $(SINGLE_CERTIFICATE)
LOCAL_SRC_FILES    := $(SINGLE_TARGET)
include $(BUILD_PREBUILT)