#The file is automatically generated!
#Add all subdir files to PRODUCT_PACKAGES

PRODUCT_PACKAGES += \
    SogouInput_36257_android_oem_oppo_20130830.apk \
    BaiduInput_Android_3-2-6-34_1001000c_oppo.apk \
    MYoungPRCMedium.apk \
    MHeiPRCMedium.apk \
    20130625180348734_12025QQ_2012_3.0_rp_release.apk \
    LocationEM.apk \
    UserDictionaryProvider.apk \
    liblocSDK_2_5OEM.so \
    features.xml \
    com.google.android.maps.xml \
    GoogleLoginService.apk \
    NetworkLocation.apk \
    BackupRestoreConfirmation.apk \
    GoogleNetworkLocation.apk \
    com.google.android.maps.jar \
    GoogleServicesFramework.apk \
    GoogleContactsSyncAdapter.apk \
    GoogleCalendarSyncAdapter.apk \
    Provision.apk \
    SharedStorageBackup.apk \
    FeedbackService.apk \
    Feedback.apk \
    SystemUI.apk \
    OppoSmallWeatherWidget.apk \
    OppoCalendarWidget.apk \
    OppoDigitalClockWidget.apk \
    ApplicationsProvider.apk \
    OppoPrivateMusicPage.apk \
    OppoPrivateMoodAlbum.apk \
    OppoLivepaper.apk \
    OppoWallpaperMgr.apk \
    HoloSpiralWallpaper.apk \
    LiveWallpapers.apk \
    LiveWallpapersPicker.apk \
    MagicSmokeWallpapers.apk \
    FreeWeatherLiveWallpaper.apk \
    Galaxy4.apk \
    PhaseBeam.apk \
    VisualizationWallpapers.apk \
    NoiseField.apk \
    PackageInstaller.apk \
    OppoLauncherSystem.apk \
    OppoLockScreenManager.apk \
    OppoLockScreenWeather.apk \
    OppoLockScreenTravel.apk \
    OppoLockScreenCard.apk \
    OppoSimUnlockScreen.apk \
    OppoPatternUnlock.apk \
    OppoLockScreenGlassBoard.apk \
    OppoLockScreenOrignal.apk \
    OppoPasswordUnlock.apk \
    OppoLauncher.apk \
    OppoKinectService.apk \
    .project \
    PartnerBookmarksProvider.apk \
    Blacklist.apk \
    Browser.apk \
    Contacts.apk \
    ContactsProvider.apk \
    DefaultContainerService.apk \
    Email.apk \
    Mms.apk \
    DownloadProvider.apk \
    KeyChain.apk \
    VpnDialogs.apk \
    CertInstaller.apk \
    Exchange.apk \
    TelephonyProvider.apk \
    PhoneNOAreaInquireProvider.apk \
    HTMLViewer.apk \
    UCService-release-V2.4.apk \
    NearMeReader_ROM_20130813_release_V2.0.apk \
    NearMeOcloud_20130823_rom_multi.apk \
    NearMeC2U.apk \
    OppoCommunity_4.1.0_3952_2013-08-23.apk \
    NearMeNote_2.2.2_color_rom_release_20130824.apk \
    RomUpdateService.apk \
    NearMeDCS_20130822_release_1.2.1_2322.apk \
    NearMeMarket_opporom_20130824_release_2.3.5.apk \
    GameCenter_opporom_20130830_release_3.3.0.apk \
    UserCenter-release-V2.4.apk \
    NearMeBackUp_20130827_rom_multi.apk \
    ThemeSpace_8_28_release_new.apk \
    FindMyPhone_20130823_rom_multi.apk \
    ThemeSpaceLib-release.apk \
    OppoSecureSafeProvider.apk \
    OppoPureBackground.apk \
    OppoOTA.apk \
    TrafficMonitor.apk \
    PowerManager.apk \
    OppoAfterService.apk \
    OppoSecureSafe.apk \
    SettingsProvider.apk \
    VistorMode.apk \
    HolidayMode.apk \
    Calendar.apk \
    FileManager.apk \
    PermissionsProvider.apk \
    BackupRestoreRemoteService.apk \
    QuickSearchBox.apk \
    OppoGesture.apk \
    OppoUsbSelection.apk \
    OppoLockNow.apk \
    OppoDriveMode.apk \
    OppoBootReg.apk \
    OppoSecureService.apk \
    OppoGestureGuide.apk \
    CalendarProvider.apk \
    Clock.apk \
    OppoPreventMode.apk \
    Calculator.apk \
    IFlySpeechService.apk \
    OppoCompass.apk \
    OppoSpeechService.apk \
    OppoSpeechAssist.apk \
    OppoWeatherLocationService.apk \
    OppoWeather.apk \
    OppoFlashLight.apk \
    BackupAndRestore.apk \
    Settings.apk \
    VideoPlug_3.8.0.1_release_20130625.apk \
    CMCCWifi_Android_6.5.0613_release.apk \
    haoboguanjia.apk \
    MusicPlugn_Android_release_3.8.0.1_20130719_1516.apk \
    MobileMusic40801_2013062415_oppo_x909t.apk \
    MM3.7_online_mab_nolog_5410011577.apk \
    Manshang_Android.3.4.0607.oppo_x909t.20130625.apk \
    MMPlayerDM_3.7.0.2_release_20130709.apk \
    MMcartoonPlug_3.7.0.7_Release_build0719.apk \
    GameHallAndroidNew_Signed_3.9.2.0_2013052489_Embeded.apk \
    MV_WR_Android2.X_Ver03.00.01.14_000078_99000-100100010010001.apk \
    lingxi_v1.0.1189_16015157.apk \
    MobilePortal.apk \
    AdobeFlashPlayer.apk \
    OppoSwitchPro.apk \
    NoteBook.apk \
    OppoGallery2.apk \
    VideoGallery.apk \
    NewSoundRecorder.apk \
    MediaProvider.apk \
    etao_huoyan.apk \
    OppoMusic.apk \
    CodeOnly \
